groups:
- name: creditinstitute-alerts
  rules:

# from jonas
  - alert: Availability1
    expr: 'avg_over_time(probe_success[1m]) < 0.8'
    labels:
      severity: error
    annotations:
      summary: "Bad Availability on {{ $labels.instance }} /  {{ $labels.target }}"


# from that 'blue book'
  - alert: Availability2
    expr: probe_success == 0
    for: 10s
    labels:
      severity: error
    annotations:
      summary: "Instance down for more than 10 s. {{ $labels.instance }} /  {{ $labels.target }}"
#
  - alert: APIHighRequestLatency
    expr: http_server_requests_seconds{quantile="0.5"} > 1.5
    for: 10m
    annotations:
      summary: "High request latency on {{ $labels.instance }}"
      description: "{{ $labels.instance }} has a median request latency above 1.5s (current value: {{ $value }}s)"
