apiVersion: v1
kind: Service
metadata:
  labels:
    app: e2etest
  name: e2etest
spec:
  ports:
    - port: 80
      targetPort: 8080
  selector:
    app: e2etest
---
apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app: e2etest
  name: e2etest
spec:
  replicas: 1
  selector:
    matchLabels:
      app: e2etest
  template:
    metadata:
      labels:
        app: e2etest
    spec:
      containers:
        - name: e2etest
          image: stiesssh/e2etest:v0.1.0
          ports:
            - containerPort: 8080
          imagePullPolicy: Always
          env:
            - name: EVENTUATELOCAL_KAFKA_BOOTSTRAP_SERVERS
              value: kafka-hs:9093
            - name: EVENTUATELOCAL_ZOOKEEPER_CONNECTION_STRING
              value: zk-hs:2181
            - name: SPRING_DATASOURCE_DRIVER_CLASS_NAME
              value: org.postgresql.Driver
            - name: SPRING_DATASOURCE_PASSWORD
              value: eventuate
            - name: SPRING_DATASOURCE_URL
              value: jdbc:postgresql://postgres/eventuate
            - name: SPRING_DATASOURCE_USERNAME
              value: eventuate
            - name: SPRING_MONGO_URL
              value: mongodb://mongo-hs:27017/data
            - name: T2_ORCHESTRATOR_URL
              value: http://orchestrator-cs/order/
      restartPolicy: Always
