apiVersion: v1
kind: Service
metadata:
  labels:
    app: orchestrator-cs
  name: orchestrator-cs
spec:
  selector:
    app: orchestrator
  ports:
  - port: 80
    targetPort: 8080
---
apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app: orchestrator
  name: orchestrator
spec:
  replicas: 1
  selector:
    matchLabels:
      app: orchestrator
  template:
    metadata:
      labels:
        app: orchestrator
    spec:
      containers:
        - name: orchestrator
          imagePullPolicy: Always
          env:
            - name: EVENTUATELOCAL_KAFKA_BOOTSTRAP_SERVERS
              value: kafka:9092
            - name: EVENTUATELOCAL_ZOOKEEPER_CONNECTION_STRING
              value: kafka-zookeeper:2181
            - name: SPRING_DATASOURCE_DRIVER_CLASS_NAME
              value: org.postgresql.Driver
            - name: SPRING_DATASOURCE_PASSWORD
              value: eventuate
            - name: SPRING_DATASOURCE_URL
              value: jdbc:postgresql://postgres/eventuate
            - name: SPRING_DATASOURCE_USERNAME
              value: eventuate
            - name: JAEGER_SERVICE_NAME
              value: orchestrator
            - name: JAEGER_ENABLE
              value: "TRUE"
            - name: JAEGER_HOST
              value: jaeger-agent
          image: stiesssh/orchestrator:v0.1.0
          ports:
            - containerPort: 8080
      restartPolicy: Always
