apiVersion: v1
kind: Service
metadata:
  labels:
    app: orchestrator-cs
  name: orchestrator-cs
spec:
  selector:
    app: inventory
  ports:
  - port: 80
    targetPort: 8080
---
apiVersion: v1
kind: Service
metadata:
  labels:
    app: orchestrator-ext
  name: orchestrator-ext
spec:
  ports:
    - port: 8084
      targetPort: 8080
  selector:
    app: orchestrator
  type: LoadBalancer
---
apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app: orchestrator
  name: orchestrator
spec:
  replicas: 1
  selector:
    matchLabels:
      app: orchestrator
  template:
    metadata:
      labels:
        app: orchestrator
    spec:
      containers:
        - name: orchestrator
          imagePullPolicy: Never
          env:
            - name: EVENTUATELOCAL_KAFKA_BOOTSTRAP_SERVERS
              value: kafka-hs:9093
            - name: EVENTUATELOCAL_ZOOKEEPER_CONNECTION_STRING
              value: zk-hs:2181
            - name: SPRING_DATASOURCE_DRIVER_CLASS_NAME
              value: org.postgresql.Driver
            - name: SPRING_DATASOURCE_PASSWORD
              value: eventuate
            - name: SPRING_DATASOURCE_URL
              value: jdbc:postgresql://postgres/eventuate
            - name: SPRING_DATASOURCE_USERNAME
              value: eventuate
          image: orchestrator
          ports:
            - containerPort: 8080
      restartPolicy: Always
