apiVersion: v1
kind: Pod
metadata:
  name: kafka-test-1
spec:
  containers:
  - command:
    - sh
    - -c
    - exec tail -f /dev/null
    image: confluentinc/cp-kafka:4.1.2-2
    imagePullPolicy: IfNotPresent
    name: kafka-test
    resources: {}
