apiVersion: v1
kind: Service
metadata:
  labels:
    app: cart-cs
  name: cart-cs
spec:
  selector:
    app: cart
  ports:
    - port: 80
      targetPort: 8080
---
apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app: cart
  name: cart
spec:
  replicas: 1
  selector:
    matchLabels:
      app: cart
  template:
    metadata:
      labels:
        app: cart
    spec:
      containers:
        - name: cart
          imagePullPolicy: Always
          env:
            - name: MONGO_URL
              value: mongodb://mongo-hs:27017/data
            - name: T2_CART_TTL
              value: "0"
            - name: T2_CART_TASKRATE
              value: "0"
          image: stiesssh/cart:v0.1.0
          ports:
            - containerPort: 8080
      restartPolicy: Always
